"""corrected column name

Revision ID: 147ac7e9d99b
Revises: 6ac068b12a79
Create Date: 2025-12-26 13:59:08.935952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147ac7e9d99b'
down_revision: Union[str, Sequence[str], None] = '6ac068b12a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Courses', sa.Column('InstructorId', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('Courses_IntructorId_fkey'), 'Courses', type_='foreignkey')
    op.create_foreign_key(None, 'Courses', 'Users', ['InstructorId'], ['id'])
    op.drop_column('Courses', 'IntructorId')
    op.add_column('Lessons', sa.Column('IntructorId', sa.String(), nullable=False))
    op.drop_column('Lessons', 'IntructorName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lessons', sa.Column('IntructorName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Lessons', 'IntructorId')
    op.add_column('Courses', sa.Column('IntructorId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Courses', type_='foreignkey')
    op.create_foreign_key(op.f('Courses_IntructorId_fkey'), 'Courses', 'Users', ['IntructorId'], ['id'])
    op.drop_column('Courses', 'InstructorId')
    # ### end Alembic commands ###
