"""corrected lessons column name instructor

Revision ID: 455faae91cf0
Revises: 147ac7e9d99b
Create Date: 2025-12-26 14:21:39.454115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455faae91cf0'
down_revision: Union[str, Sequence[str], None] = '147ac7e9d99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lessons', sa.Column('InstructorId', sa.String(), nullable=False))
    op.drop_column('Lessons', 'IntructorId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lessons', sa.Column('IntructorId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Lessons', 'InstructorId')
    # ### end Alembic commands ###
