"""create_questions_table

Revision ID: 5b7824d6c9b3
Revises: add_fk_enrollments_studentid
Create Date: 2026-01-13 16:36:48.353491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7824d6c9b3'
down_revision: Union[str, Sequence[str], None] = 'add_fk_enrollments_studentid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Questions',
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('QuizId', sa.Integer(), nullable=False),
    sa.Column('Questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['QuizId'], ['Quizzes.QuizId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('QuestionId')
    )
    op.create_index(op.f('ix_Questions_QuestionId'), 'Questions', ['QuestionId'], unique=False)
    op.create_index(op.f('ix_Questions_QuizId'), 'Questions', ['QuizId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Questions_QuizId'), table_name='Questions')
    op.drop_index(op.f('ix_Questions_QuestionId'), table_name='Questions')
    op.drop_table('Questions')
    # ### end Alembic commands ###
