"""create tables

Revision ID: 6ac068b12a79
Revises: 6f023ed2bac8
Create Date: 2025-12-26 11:07:56.660104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac068b12a79'
down_revision: Union[str, Sequence[str], None] = '6f023ed2bac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('CategoryId', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('CategoryId'),
    sa.UniqueConstraint('CategoryName')
    )
    op.create_index(op.f('ix_Category_CategoryId'), 'Category', ['CategoryId'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_table('Courses',
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('CourseName', sa.String(), nullable=False),
    sa.Column('Categoryid', sa.Integer(), nullable=False),
    sa.Column('IntructorId', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['Categoryid'], ['Category.CategoryId'], ),
    sa.ForeignKeyConstraint(['IntructorId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('courseId'),
    sa.UniqueConstraint('CourseName')
    )
    op.create_index(op.f('ix_Courses_courseId'), 'Courses', ['courseId'], unique=False)
    op.create_table('Enrollments',
    sa.Column('Enrollmentnumber', sa.Integer(), nullable=False),
    sa.Column('StudentId', sa.Integer(), nullable=False),
    sa.Column('CourseId', sa.Integer(), nullable=False),
    sa.Column('InstructorId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['CourseId'], ['Courses.courseId'], ),
    sa.PrimaryKeyConstraint('Enrollmentnumber')
    )
    op.create_index(op.f('ix_Enrollments_Enrollmentnumber'), 'Enrollments', ['Enrollmentnumber'], unique=False)
    op.create_table('Lessons',
    sa.Column('lessonnumber', sa.Integer(), nullable=False),
    sa.Column('lessonName', sa.String(), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('IntructorName', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['Courses.courseId'], ),
    sa.PrimaryKeyConstraint('lessonnumber', 'courseId', name='lessons_pk'),
    sa.UniqueConstraint('lessonName')
    )
    op.create_index(op.f('ix_Lessons_lessonnumber'), 'Lessons', ['lessonnumber'], unique=False)
    op.create_table('Quizzes',
    sa.Column('QuizId', sa.Integer(), nullable=False),
    sa.Column('QuizTopic', sa.String(), nullable=False),
    sa.Column('CourseId', sa.Integer(), nullable=False),
    sa.Column('InstructorId', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['CourseId'], ['Courses.courseId'], ),
    sa.PrimaryKeyConstraint('QuizId'),
    sa.UniqueConstraint('QuizTopic')
    )
    op.create_index(op.f('ix_Quizzes_QuizId'), 'Quizzes', ['QuizId'], unique=False)
    op.create_table('QuizScore',
    sa.Column('QuizId', sa.Integer(), nullable=False),
    sa.Column('StudentId', sa.Integer(), nullable=False),
    sa.Column('QuizScore', sa.Integer(), nullable=True),
    sa.Column('CourseId', sa.Integer(), nullable=False),
    sa.Column('InstructorId', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['CourseId'], ['Courses.courseId'], ),
    sa.ForeignKeyConstraint(['QuizId'], ['Quizzes.QuizId'], ),
    sa.ForeignKeyConstraint(['StudentId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('QuizId', 'StudentId', name='quizscore_pk')
    )
    op.create_index(op.f('ix_QuizScore_QuizId'), 'QuizScore', ['QuizId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_QuizScore_QuizId'), table_name='QuizScore')
    op.drop_table('QuizScore')
    op.drop_index(op.f('ix_Quizzes_QuizId'), table_name='Quizzes')
    op.drop_table('Quizzes')
    op.drop_index(op.f('ix_Lessons_lessonnumber'), table_name='Lessons')
    op.drop_table('Lessons')
    op.drop_index(op.f('ix_Enrollments_Enrollmentnumber'), table_name='Enrollments')
    op.drop_table('Enrollments')
    op.drop_index(op.f('ix_Courses_courseId'), table_name='Courses')
    op.drop_table('Courses')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Category_CategoryId'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
